# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OneKeySDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OneKeySDKDemo
  pod 'OneKeySDK', :path => '../../'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'lottie-ios'
  pod 'FlexColorPicker'
  pod 'IQKeyboardManagerSwift'
  
  target 'OneKeySDKDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OneKeySDKDemoUITests' do
    # Pods for testing
  end

end
