//
//  Theme+Additional.swift
//  HealthCareLocatorSDKDemo
//
//  Created by Truong Le on 12/8/20.
//

import Foundation
import UIKit

extension Theme {
    static let defaultGreenTheme = Theme(defaultFont: FontInfo(fontName: defaultSystemFontName, fontSize: 14.0),
                                             titleMainFont: FontInfo(fontName: defaultSystemFontName, fontSize: 20.0),
                                             titleSecondaryFont: FontInfo(fontName: defaultSystemBoldFontName, fontSize: 16.0),
                                             searchResultTotalFont: FontInfo(fontName: defaultSystemBoldFontName, fontSize: 14.0),
                                             searchResultTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                             resultTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 14.0),
                                             resultSubTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 14.0),
                                             profileTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 18.0),
                                             profileSubTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                             profileTitleSectionFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                             cardTitleFont: FontInfo(fontName: defaultSystemBoldFontName, fontSize: 16.0),
                                             modalTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 18.0),
                                             searchInputFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                             sortCriteriaFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                             buttonFont: FontInfo(fontName: defaultSystemFontName, fontSize: 14.0),
                                             smallFont: FontInfo(fontName: defaultSystemFontName, fontSize: 12.0),
                                             noResultTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 20.0),
                                             noResultDescFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                             primaryColor: "43b02a",
                                             secondaryColor: "00a3e0",
                                             buttonBkgColor: "fcfcfc",
                                             buttonAcceptBkgColor: "43b02a",
                                             buttonDiscardBkgColor: "9aa0a7",
                                             buttonBorderColor: "dedede",
                                             cardBorderColor: "dedede",
                                             markerColor: "fe8a12",
                                             markerSelectedColor: "fd8670",
                                             viewBkgColor: "f8f9fa",
                                             listBkgColor: "f8f9fa",
                                             voteUpColor: "43b02a",
                                             voteDownColor: "ff0000",
                                             darkColor: "2b3c4d",
                                             greyColor: "a1a1a1",
                                             greyDarkColor: "7d7d7d",
                                             greyDarkerColor: "666666",
                                             greyLightColor: "b8b8b8",
                                             greyLighterColor: "ebebeb")
    
    static let defaultBlueTheme = Theme(defaultFont: FontInfo(fontName: defaultSystemFontName, fontSize: 14.0),
                                            titleMainFont: FontInfo(fontName: defaultSystemFontName, fontSize: 20.0),
                                            titleSecondaryFont: FontInfo(fontName: defaultSystemBoldFontName, fontSize: 16.0),
                                            searchResultTotalFont: FontInfo(fontName: defaultSystemBoldFontName, fontSize: 14.0),
                                            searchResultTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                            resultTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 14.0),
                                            resultSubTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 14.0),
                                            profileTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 18.0),
                                            profileSubTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                            profileTitleSectionFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                            cardTitleFont: FontInfo(fontName: defaultSystemBoldFontName, fontSize: 16.0),
                                            modalTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 18.0),
                                            searchInputFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                            sortCriteriaFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                            buttonFont: FontInfo(fontName: defaultSystemFontName, fontSize: 14.0),
                                            smallFont: FontInfo(fontName: defaultSystemFontName, fontSize: 12.0),
                                            noResultTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 20.0),
                                            noResultDescFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                            primaryColor: "0433CC",
                                            secondaryColor: "B3C6FF",
                                            buttonBkgColor: "fcfcfc",
                                            buttonAcceptBkgColor: "0433CC",
                                            buttonDiscardBkgColor: "9aa0a7",
                                            buttonBorderColor: "dedede",
                                            cardBorderColor: "dedede",
                                            markerColor: "1A53FF",
                                            markerSelectedColor: "000D33",
                                            viewBkgColor: "f8f9fa",
                                            listBkgColor: "f8f9fa",
                                            voteUpColor: "0433CC",
                                            voteDownColor: "ff0000",
                                            darkColor: "2b3c4d",
                                            greyColor: "a1a1a1",
                                            greyDarkColor: "7d7d7d",
                                            greyDarkerColor: "666666",
                                            greyLightColor: "b8b8b8",
                                            greyLighterColor: "ebebeb")
    
    
    static let defaultRedTheme = Theme(defaultFont: FontInfo(fontName: defaultSystemFontName, fontSize: 14.0),
                                           titleMainFont: FontInfo(fontName: defaultSystemFontName, fontSize: 20.0),
                                           titleSecondaryFont: FontInfo(fontName: defaultSystemBoldFontName, fontSize: 16.0),
                                           searchResultTotalFont: FontInfo(fontName: defaultSystemBoldFontName, fontSize: 14.0),
                                           searchResultTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                           resultTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 14.0),
                                           resultSubTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 14.0),
                                           profileTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 18.0),
                                           profileSubTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                           profileTitleSectionFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                           cardTitleFont: FontInfo(fontName: defaultSystemBoldFontName, fontSize: 16.0),
                                           modalTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 18.0),
                                           searchInputFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                           sortCriteriaFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                           buttonFont: FontInfo(fontName: defaultSystemFontName, fontSize: 14.0),
                                           smallFont: FontInfo(fontName: defaultSystemFontName, fontSize: 12.0),
                                           noResultTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 20.0),
                                           noResultDescFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                           primaryColor: "FD0D00",
                                           secondaryColor: "FECCCC",
                                           buttonBkgColor: "fcfcfc",
                                           buttonAcceptBkgColor: "FD0D00",
                                           buttonDiscardBkgColor: "9aa0a7",
                                           buttonBorderColor: "dedede",
                                           cardBorderColor: "dedede",
                                           markerColor: "FD3334",
                                           markerSelectedColor: "4D0100",
                                           viewBkgColor: "f8f9fa",
                                           listBkgColor: "f8f9fa",
                                           voteUpColor: "FD0D00",
                                           voteDownColor: "ff0000",
                                           darkColor: "2b3c4d",
                                           greyColor: "a1a1a1",
                                           greyDarkColor: "7d7d7d",
                                           greyDarkerColor: "666666",
                                           greyLightColor: "b8b8b8",
                                           greyLighterColor: "ebebeb")
    
    static let defaultPurpleTheme = Theme(defaultFont: FontInfo(fontName: defaultSystemFontName, fontSize: 14.0),
                                              titleMainFont: FontInfo(fontName: defaultSystemFontName, fontSize: 20.0),
                                              titleSecondaryFont: FontInfo(fontName: defaultSystemBoldFontName, fontSize: 16.0),
                                              searchResultTotalFont: FontInfo(fontName: defaultSystemBoldFontName, fontSize: 14.0),
                                              searchResultTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                              resultTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 14.0),
                                              resultSubTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 14.0),
                                              profileTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 18.0),
                                              profileSubTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                              profileTitleSectionFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                              cardTitleFont: FontInfo(fontName: defaultSystemBoldFontName, fontSize: 16.0),
                                              modalTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 18.0),
                                              searchInputFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                              sortCriteriaFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                              buttonFont: FontInfo(fontName: defaultSystemFontName, fontSize: 14.0),
                                              smallFont: FontInfo(fontName: defaultSystemFontName, fontSize: 12.0),
                                              noResultTitleFont: FontInfo(fontName: defaultSystemFontName, fontSize: 20.0),
                                              noResultDescFont: FontInfo(fontName: defaultSystemFontName, fontSize: 16.0),
                                              primaryColor: "771d5f",
                                              secondaryColor: "e5cee4",
                                              buttonBkgColor: "fcfcfc",
                                              buttonAcceptBkgColor: "771d5f",
                                              buttonDiscardBkgColor: "9aa0a7",
                                              buttonBorderColor: "dedede",
                                              cardBorderColor: "dedede",
                                              markerColor: "a33c9f",
                                              markerSelectedColor: "690f65",
                                              viewBkgColor: "f8f9fa",
                                              listBkgColor: "f8f9fa",
                                              voteUpColor: "771d5f",
                                              voteDownColor: "ff0000",
                                              darkColor: "2b3c4d",
                                              greyColor: "a1a1a1",
                                              greyDarkColor: "7d7d7d",
                                              greyDarkerColor: "666666",
                                              greyLightColor: "b8b8b8",
                                              greyLighterColor: "ebebeb")
}
