stages:
  - prepare
  - build
  - deploy

prepare:install-pods:
  interruptible: true
  stage: prepare
  tags:
    - ios
  except:
    - tags
  before_script:
    - cd ./Example/OneKeySDKDemo/
  script:
    - bundle install
    - bundle exec pod install
  cache:
    key:
      files:
        - Gemfile.lock
        - Podfile.lock
    paths:
      - Pods/
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_SLUG}_dependencies"
    expire_in: 1 hour
    paths:
      - Pods/

prepare:clean:
  interruptible: true
  stage: prepare
  tags:
    - ios
  except:
    - tags
  before_script:
    - cd ./Example/OneKeySDKDemo/
  script:
    - rm -rf reports build ~/Library/Developer/Xcode/DerivedData/Spacetime*
    - xcodebuild clean -workspace OneKeySDKDemo.xcworkspace -scheme OneKeySDKDemo | xcpretty

build:mr:
  interruptible: true
  stage: build
  tags:
    - ios
  only:
    - branches
  except:
    - develop
    - master
    - release
    - hotfixes
    - tags
  script:
    - xcodebuild build -workspace OneKeySDKDemo.xcworkspace -scheme OneKeySDKDemo -configuration Release -derivedDataPath build -allowProvisioningUpdates | xcpretty -s
  needs:
    - job: prepare:install-pods
      artifacts: true

## Dev app: Build and deploy
build:dev:
  extends: .build
  only:
    - develop
  script:
    - xcodebuild archive -workspace OneKeySDKDemo.xcworkspace -scheme OneKeySDKDemo -configuration Release -archivePath build/OneKeySDKDemo.xcarchive -derivedDataPath build -allowProvisioningUpdates | xcpretty -s;
    - xcodebuild -exportArchive -archivePath "build/OneKeySDKDemo.xcarchive" -exportOptionsPlist exportInHouseOptions.plist -exportPath build -allowProvisioningUpdates | xcpretty -s;
    - ditto -c -k -rsrc build/OneKeySDKDemo.xcarchive/dSYMs build/OneKeySDKDemo-dSYM.zip
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_SLUG}_release-dev"
    expire_in: 30 days
    paths:
      - build/OneKeySDKDemo.ipa
      - build/OneKeySDKDemo.zip
      - build/OneKeySDKDemo.xcarchive

deploy:dev:
  extends: .deploy
  only:
    - develop
  script:
    - VERSION=$(/usr/libexec/PlistBuddy -c "Print :ApplicationProperties:CFBundleShortVersionString" "${PWD}/build/OneKeySDKDemo.xcarchive/Info.plist") bundle exec fastlane dev_deploy
  needs:
    - job: build:dev
      artifacts: true

## Templates
.build:
  interruptible: true
  stage: build
  tags:
    - ios
  before_script:
    - rm -rf container/*
    - /usr/bin/agvtool new-version -all $CI_PIPELINE_IID
  allow_failure: false
  needs:
    - job: prepare:install-pods
      artifacts: true

.deploy:
  stage: deploy
  tags:
    - ios
  variables:
    BUILD_NUMBER: "${CI_PIPELINE_IID}"
  before_script:
    # Force to use SSH (for tags pushing)
    - git remote set-url origin git@gitlab.ekino.com:iqvia/OneKeySDK-iOS.git
    - cd ./Example/OneKeySDKDemo/
    - bundle install
    - bundle update fastlane
    - git fetch --all --tags
  allow_failure: false
