
trigger:
  branches:
   include:
   - release/*
  tags: 
   include:
   - '*'

pool:
  vmImage: "macos-latest"

variables:
  p12Password: $(p12Secret)

stages:
  - stage: BuildNumberGenerator  
    displayName: Build Version Tag
    jobs:
    - job: GenerateReleaseVersionTag
      condition: startsWith(variables['build.sourceBranch'], 'refs/heads/release/')
      variables: 
        revision: $[counter(variables['build.sourcebranchname'], 0)]
      steps:
      - bash: echo '##vso[build.updatebuildnumber]r$(build.sourcebranchname)-$(revision)'

    - job: GenerateMasterVersionTag
      condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')
      variables: 
        revision: $[counter(variables['build.sourceBranch'], 0)]
      steps:
      - bash: echo '##vso[build.updatebuildnumber]$(build.sourcebranchname)'

  - stage: BuildSteps
    jobs:
    - job: Build 
      condition: or(startsWith(variables['build.sourceBranch'], 'refs/heads/release/'), startsWith(variables['build.sourceBranch'], 'refs/tags/')) 
      steps:
      - checkout: self
        path: s/onekey-sdk-ios-lib

      - task: ios-bundle-version@1
        inputs:
          sourcePath: "Example/HealthCareLocatorSDKDemo/HCLDemo-Info.plist"
          versionCodeOption: "buildid"
          versionCode: "$(Build.BuildId)"
          versionCodeOffset: "0"
          printFile: true

      - task: XplatGenerateReleaseNotes@3
        displayName: "Generare Release notes"
        inputs:
          outputfile: 'release.txt'
          templateLocation: 'InLine'
          inlinetemplate: |
            ## Build {{buildDetails.buildNumber}}
            * **Branch**: {{buildDetails.sourceBranch}}
            * **Tags**: {{buildDetails.tags}}
            * **Completed**: {{buildDetails.finishTime}}
            * **Previous Build**: {{compareBuildDetails.buildNumber}}

            ## Associated Pull Requests ({{pullRequests.length}})
            {{#forEach pullRequests}}
            * **[{{this.pullRequestId}}]({{replace (replace this.url "_apis/git/repositories" "_git") "pullRequests" "pullRequest"}})** {{this.title}}
            * Associated Work Items
                {{#forEach this.associatedWorkitems}}
                    {{#with (lookup_a_work_item ../../relatedWorkItems this.url)}}
                        - [{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}}) - {{lookup this.fields 'System.Title'}}
                    {{/with}}
                {{/forEach}}
            * Associated Commits (this includes commits on the PR source branch not associated directly with the build)
                {{#forEach this.associatedCommits}}
                    - [{{this.commitId}}]({{this.remoteUrl}}) -  {{this.comment}}
                {{/forEach}}
            {{/forEach}}
          dumpPayloadToConsole: true
          dumpPayloadToFile: false
          replaceFile: true
          getParentsAndChildren: False
          getAllParents: False
          getIndirectPullRequests: False
          stopOnError: False
          considerPartiallySuccessfulReleases: False


      - task: InstallAppleCertificate@2
        inputs:
          certSecureFile: "IQVIA-2022.p12"
          certPwd: "$(p12Password)"
          keychain: "temp"
          deleteCert: true

      - task: InstallAppleProvisioningProfile@1
        inputs:
          provisioningProfileLocation: "secureFiles"
          provProfileSecureFile: "hclapp.mobileprovision"
          removeProfile: true

      - task: CocoaPods@0
        inputs:
          forceRepoUpdate: false
          projectDirectory: Example/HealthCareLocatorSDKDemo

      - task: Xcode@5
        inputs:
          actions: "archive"
          scheme: "HCLDemo"
          sdk: "iphoneos"
          configuration: "Release"
          xcWorkspacePath: "Example/HealthCareLocatorSDKDemo/HealthCareLocatorSDKDemo.xcworkspace"
          xcodeVersion: "default"
          signingOption: "manual"
          useXcpretty: false
          signingIdentity: "$(APPLE_CERTIFICATE_SIGNING_IDENTITY)"
          provisioningProfileUuid: "$(APPLE_PROV_PROFILE_UUID)"
          packageApp: true

      - task: CopyFiles@2
        inputs:
          contents: "**/*.ipa"
          targetFolder: "$(build.artifactStagingDirectory)"
          overWrite: true
          flattenFolders: true

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: "$(build.artifactStagingDirectory)"
          artifactName: "drop"
          publishLocation: "Container"
