# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:

- task: CocoaPods@0
  inputs:
    forceRepoUpdate: 
    projectDirectory: Example/OneKeySDKDemo

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'OneKeySDKDemo'
    sdk: 'Generic iOS Device'
    configuration: 'Release'
    xcWorkspacePath: 'Example/OneKeySDKDemo/OneKeySDKDemo.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' 
