
trigger:
  branches:
   include:
   - master
  tags: 
   include:
   - '*'

pool:
  vmImage: "macos-latest"

variables:
  p12Password: $(p12Secret)

stages:
  - stage: BuildNumberGenerator  
    displayName: Build Version Tag
    jobs:
    - job: GenerateReleaseVersionTag
      condition: startsWith(variables['build.sourceBranch'], 'refs/heads/release/')
      variables: 
        revision: $[counter(variables['build.sourcebranchname'], 0)]
      steps:
      - bash: echo '##vso[build.updatebuildnumber]r$(build.sourcebranchname)-$(revision)'

    - job: GenerateMasterVersionTag
      condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')
      variables: 
        revision: $[counter(variables['build.sourceBranch'], 0)]
      steps:
      - bash: echo '##vso[build.updatebuildnumber]$(build.sourcebranchname)'

  - stage: BuildSteps
    jobs:
    - job: Build 
      condition: or(startsWith(variables['build.sourceBranch'], 'refs/heads/release/'), startsWith(variables['build.sourceBranch'], 'refs/tags/')) 
      steps:
      - checkout: self
        path: s/onekey-sdk-ios-lib

      - task: InstallAppleCertificate@2
        inputs:
          certSecureFile: "IQVIA-2022.p12"
          certPwd: "$(p12Password)"
          keychain: "temp"
          deleteCert: true

      - task: InstallAppleProvisioningProfile@1
        inputs:
          provisioningProfileLocation: "secureFiles"
          provProfileSecureFile: "hclapp.mobileprovision"
          removeProfile: true

      - task: CocoaPods@0
        inputs:
          forceRepoUpdate: false
          projectDirectory: .

      - task: Xcode@5
        inputs:
          actions: "archive"
          scheme: "HealthCareLocatorSDK"
          sdk: "iphoneos"
          configuration: "Release"
          xcWorkspacePath: "HealthCareLocatorSDK.xcworkspace"
          xcodeVersion: "default"
          signingOption: "manual"
          useXcpretty: false
          signingIdentity: "$(APPLE_CERTIFICATE_SIGNING_IDENTITY)"
          provisioningProfileUuid: "$(APPLE_PROV_PROFILE_UUID)"
          packageApp: false

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: "$(build.artifactStagingDirectory)"
          artifactName: "drop"
          publishLocation: "Container"
