# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
ensure_bundle_exec

default_platform(:ios)

is_releasable = nil
build_number = nil
next_version = nil
snapshot_version = nil
release_next = nil
notes = nil
tag_name = nil

before_all do |options, params|
  full_version = ENV["VERSION"] || "1.0.0"
  # next_version = /^\d+\.\d+(\.\d+)?/.match(full_version)
  next_version = "1.0.0"
  puts "next_version: #{next_version}"
  build_number = ENV["BUILD_NUMBER"] || 1
  puts "build_number: #{build_number}"
  snapshot_version = "#{full_version} (#{build_number})"
  puts "snapshot_version: #{snapshot_version}"
end

private_lane :verify do |options|
  config = options[:config]
  puts "config: #{config}"

  is_releasable = analyze_commits(match: "#{config}/*")
  puts "is_releasable: #{is_releasable}"

  if is_releasable then
    notes = conventional_changelog(format: 'markdown')
    release_next = lane_context[SharedValues::RELEASE_NEXT_VERSION]
    notes.gsub! "#{release_next}", "#{snapshot_version}"
    puts "changelog: #{notes}"

    tag_name = "#{config}/#{next_version}/#{build_number}"
    puts "tag_name: #{tag_name}"
  end

  is_releasable
end

platform :ios do
  desc "Upload dev app to AppCenter"
  lane :dev_deploy do

    next unless verify(config: "dev")

    appcenter_upload(
      owner_name: "contact-c08l",
      app_name: "OneKeySDKDemo",
      file: "./build/HealthCareLocatorSDKDemo.ipa",
      dsym: "./build/HealthCareLocatorSDKDemo-dSYM.zip",
      release_notes: notes,
      destinations: "Ekino-IQVIA",
      destination_type: "group",
      notify_testers: false
    )
  end
end

after_all do |lane|
  next unless is_releasable

  add_git_tag(tag: tag_name)
  push_git_tags

end
