# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'HealthCareLocatorSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HealthCareLocatorSDKDemo
  pod 'HealthCareLocatorSDK', :path => '../../'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'lottie-ios'
  pod 'FlexColorPicker'
  pod 'IQKeyboardManagerSwift'
  pod 'AppCenter'

end
